name: armoyu_services
description: 'ARMOYU kütüphanesidir'
repository: https://github.com/aramizdakioyuncu/armoyu_services
version: 1.0.0+59

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  device_info_plus: ^11.4.0
  package_info_plus: ^8.0.1
  crypto: ^3.0.3
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
