name: armoyu_services
description: "ARMOYU kütüphanesidir"
publish_to: https://pub.dev/publishers/aramizdakioyuncu.com
repository: https://github.com/berkaytikenoglu/armoyu_services
version: 1.0.0+3

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  device_info_plus: ^10.0.1
  package_info_plus: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
